[tool.black]
line-length = 120
target-version = ['py313']

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "B"]
ignore = [
    "ANN",   # Ignore all type annotation warnings
    "B904",  # Ignore exception chaining requirement
]

[tool.isort]
profile = "black"